[package]
name = "worker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
persistence-postgres.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true

[lints]
workspace = true
