[package]
name = "persistence-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
application.workspace = true
async-trait.workspace = true
domain.workspace = true
hex.workspace = true
metrics.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
adapters.workspace = true
tokio.workspace = true

[lints]
workspace = true
